FDTN-964: Add k8s cluster host registry that returns internal host names
flowcommerce/lib-util pull request #129
Opened 2022-06-10 14:01 UTC by gheine

2022-06-13 14:47 UTC, benwaffle commented on src/main/scala/io/flow/util/clients/Registry.scala
> +    case _         => s"http://$applicationId"
```suggestion
    case _         => s"http://$applicationId.production"
```

2022-06-13 14:59 UTC, benwaffle commented on src/main/scala/io/flow/util/clients/Registry.scala
> +    host
should we do a DNS lookup to validate that the record exists, before returning?

2022-06-13 17:48 UTC, gheine commented on src/main/scala/io/flow/util/clients/Registry.scala
> +    case _         => s"http://$applicationId"
@renilthomas any preference here? service or service.production?

2022-06-14 13:36 UTC, benwaffle commented on src/main/scala/io/flow/util/clients/Registry.scala
> +    host
let's also log an error for hosts that we can't resolve - we should be alerted

2022-06-15 15:42 UTC, gheine commented on src/main/scala/io/flow/util/clients/Registry.scala
> +    host
payment won't be able to resolve cluster internal host names, so it would log errors when this is expected behaviour

2022-06-15 15:47 UTC, benwaffle commented on src/main/scala/io/flow/util/clients/Registry.scala
> +    host
payment shouldn't be using the k8s registry, right?

2022-06-15 23:12 UTC, benwaffle commented on src/main/scala/io/flow/util/clients/Registry.scala
> +      Await.result(asyncDnsLookupByName(applicationId), 100.millis)
This isn't a constant, this is the prod implementation, so I moved it to ProductionRegistry from RegistryConstants

2022-06-21 23:17 UTC, benwaffle commented on src/main/scala/io/flow/util/clients/Registry.scala
> +      Await.result(asyncDnsLookupByName(applicationId), 100.millis)
@gheine ^

2022-06-22 19:43 UTC, benwaffle commented on src/main/scala/io/flow/util/clients/Registry.scala
> +      Await.result(asyncDnsLookupByName(applicationId), 100.millis)
@gheine I believe my comment here still applies to your latest commit, can you address it?

2022-06-23 16:02 UTC, benwaffle requested changes

2022-06-23 16:02 UTC, benwaffle commented on src/main/scala/io/flow/util/clients/Registry.scala
> +  private[clients] val DnsLookupWaitTime = 100.millis
can we move both of these to `ProductionRegistry` as they are DNS lookup-specific?

2022-06-23 16:02 UTC, benwaffle commented
otherwise lgtm

2022-06-23 16:03 UTC, benwaffle commented
and we should test this in a service in prod if we are not already doing that

2022-06-23 17:10 UTC, gheine commented on src/main/scala/io/flow/util/clients/Registry.scala
> +  private[clients] val DnsLookupWaitTime = 100.millis
No they're static constants, they should not be per-instance

2022-06-23 17:13 UTC, merged